// gen-assets.mjs — generate src/generated-assets.ts: the injected webview
// index.html, the bridge-client, and the REAL preload.js, bundled as strings the
// Worker serves (Workers have no runtime FS). Run before deploy/dry-run.
//
// Reads only files inside apps/codex:
//   • browser-bridge/bridge-client.js                    (committed split source)
//   • payload/linux-rehost/app/.vite/build/preload.js    (from build:payload)
//   • payload/linux-rehost/app/webview/index.html        (the renderer shell)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PAYLOAD_APP = path.join(ROOT, "payload", "linux-rehost", "app");
const WEBVIEW = path.join(PAYLOAD_APP, "webview");
const BUILD = path.join(PAYLOAD_APP, ".vite", "build");
const BB = path.join(ROOT, "browser-bridge");

const preloadPath = path.join(BUILD, "preload.js");
const indexPath = path.join(WEBVIEW, "index.html");
if (!existsSync(preloadPath) || !existsSync(indexPath)) {
  throw new Error(
    `Missing ${existsSync(preloadPath) ? indexPath : preloadPath}. Run \`npm run build:payload\` ` +
      `first to extract the Codex payload from /Applications/Codex.app.`,
  );
}

const bridgeClient = readFileSync(path.join(BB, "bridge-client.js"), "utf8");
const preload = readFileSync(preloadPath, "utf8");

// Content-hash version → cache-bust the bridge-client/preload script URLs.
const ver = createHash("sha256").update(bridgeClient + preload).digest("hex").slice(0, 12);

const inject =
  `<base href="/">` +
  `<script>window.__BRIDGE_WS_URL__=(location.protocol==="https:"?"wss://":"ws://")+location.host+"/bridge";` +
  `window.__BRIDGE_PRELOAD_URL__="/__bridge/preload.js?v=${ver}";` +
  `window.__BRIDGE_BOOT_URL__="/__bridge/boot";</script>` +
  `<script src="/__bridge/bridge-client.js?v=${ver}"></script>`;

let indexHtml = readFileSync(indexPath, "utf8");
// 1. Drop the bundle's strict CSP — it pins script-src to a build-time hash and
//    blocks the injected bridge-client + the cross-origin OpenAI/ChatGPT backend
//    connections. The Worker serves over its own origin; rely on Access for auth.
indexHtml = indexHtml.replace(/<meta http-equiv="Content-Security-Policy"[\s\S]*?>/i, "<!-- CSP stripped by gen-assets (bridge + cross-origin backend) -->");
// 2. Clear the placeholder comments the Electron main would normally fill.
indexHtml = indexHtml.replace("<!-- PROD_BASE_TAG_HERE -->", "");
indexHtml = indexHtml.replace("<!-- PROD_CSP_TAG_HERE -->", "");
// 3. Inject the bridge-client (classic script) BEFORE the SPA module so the
//    electron shim + real preload run first.
if (!/<script type="module"/.test(indexHtml)) throw new Error("webview index.html has no module script to inject before");
indexHtml = indexHtml.replace(/<script type="module"/, inject + "\n    <script type=\"module\"");

const enc = (s) => JSON.stringify(s);
const out =
  `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.\n` +
  `export const INDEX_HTML = ${enc(indexHtml)};\n` +
  `export const BRIDGE_CLIENT_JS = ${enc(bridgeClient)};\n` +
  `export const PRELOAD_JS = ${enc(preload)};\n`;
writeFileSync(path.join(ROOT, "src", "generated-assets.ts"), out);
console.log(
  JSON.stringify(
    { ok: true, indexBytes: indexHtml.length, bridgeClientBytes: bridgeClient.length, preloadBytes: preload.length, ver },
    null,
    2,
  ),
);
